bot:
  abi_migration_branches:
  - 1.1.1
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
test_on_native_only: true
build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_64
github:
  branch_name: main
  tooling_branch_name: main
